# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types:
      - closed
env:
  PORT: 8080

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependency
        run: npm ci
      - run: npm run build --if-present
      - run: npm test
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_IP }} # IP address
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD}} # Store the password securely in GitHub Secrets
          script: |
            cd /home/nizar/Projects/nodeBase  
            git fetch
            git reset --hard origin/main  # Forcefully pull the latest changes
            npm cache clean --force
            npm install            # Install any new dependencies
            pm2 stop nodeBase  # Stop the old process
            pm2 delete nodeBase  # Remove it from the PM2 process list
            pm2 start npm --name "nodeBase" -- start  # Start the new version
            pm2 save
